// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package classlibrary1;

@net.sf.jni4net.attributes.ClrType
public class GreatTest extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected GreatTest(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public GreatTest() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        classlibrary1.GreatTest.__ctorGreatTest0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorGreatTest0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/String;")
    public native java.lang.String answer(java.lang.String str);
    
    public static system.Type typeof() {
        return classlibrary1.GreatTest.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        classlibrary1.GreatTest.staticType = staticType;
    }
    //</generated-proxy>
}
